algoritmo "semnome"
var
   contador: inteiro
inicio
      contador <- 0
      enquanto contador < 10 faca
               escreval(contador)
               contador <- contador + 1
      fimenquanto
      
      repita
            escreval(contador)
            contador <- contador - 1
      ate contador < 0    3
      
      para contador <- 0 ate 10 passo 1 faca
           escreval(contador)
      fimpara
fimalgoritmo